[namelist:jules_pftparm(brd_leaf_dec)]
act_jmax_io=50.0e3
act_vcmax_io=72.0e3
alpha_elec_io=0.4
deact_jmax_io=200.0e3
deact_vcmax_io=200.0e3
ds_jmax_io=646.0
ds_vcmax_io=649.0
jv25_ratio_io=1.97

[namelist:jules_pftparm(brd_leaf_eg_temp)]
act_jmax_io=50.0e3
act_vcmax_io=72.0e3
alpha_elec_io=0.4
deact_jmax_io=200.0e3
deact_vcmax_io=200.0e3
ds_jmax_io=646.0
ds_vcmax_io=649.0
jv25_ratio_io=1.97

[namelist:jules_pftparm(brd_leaf_eg_trop)]
act_jmax_io=50.0e3
act_vcmax_io=72.0e3
alpha_elec_io=0.4
deact_jmax_io=200.0e3
deact_vcmax_io=200.0e3
ds_jmax_io=646.0
ds_vcmax_io=649.0
jv25_ratio_io=1.97

[namelist:jules_pftparm(c3_grass)]
act_jmax_io=50.0e3
act_vcmax_io=72.0e3
alpha_elec_io=0.4
deact_jmax_io=200.0e3
deact_vcmax_io=200.0e3
ds_jmax_io=646.0
ds_vcmax_io=649.0
jv25_ratio_io=1.97

[namelist:jules_pftparm(c4_grass)]
act_jmax_io=50.0e3
act_vcmax_io=72.0e3
alpha_elec_io=0.4
deact_jmax_io=200.0e3
deact_vcmax_io=200.0e3
ds_jmax_io=646.0
ds_vcmax_io=649.0
jv25_ratio_io=1.97

[namelist:jules_pftparm(ndl_leaf_dec)]
act_jmax_io=50.0e3
act_vcmax_io=72.0e3
alpha_elec_io=0.4
deact_jmax_io=200.0e3
deact_vcmax_io=200.0e3
ds_jmax_io=646.0
ds_vcmax_io=649.0
jv25_ratio_io=1.97

[namelist:jules_pftparm(ndl_leaf_eg)]
act_jmax_io=50.0e3
act_vcmax_io=72.0e3
alpha_elec_io=0.4
deact_jmax_io=200.0e3
deact_vcmax_io=200.0e3
ds_jmax_io=646.0
ds_vcmax_io=649.0
jv25_ratio_io=1.97

[namelist:jules_pftparm(shrub_dec)]
act_jmax_io=50.0e3
act_vcmax_io=72.0e3
alpha_elec_io=0.4
deact_jmax_io=200.0e3
deact_vcmax_io=200.0e3
ds_jmax_io=646.0
ds_vcmax_io=649.0
jv25_ratio_io=1.97

[namelist:jules_pftparm(shrub_eg)]
act_jmax_io=50.0e3
act_vcmax_io=72.0e3
alpha_elec_io=0.4
deact_jmax_io=200.0e3
deact_vcmax_io=200.0e3
ds_jmax_io=646.0
ds_vcmax_io=649.0
jv25_ratio_io=1.97

[namelist:jules_time]
main_run_end='1997-06-30 23:00:00'

[namelist:jules_vegetation]
photo_acclim_model=0
photo_act_model=1
photo_jv_model=1
photo_model=2
